In [1]:
from pycaret.datasets import get_data 
import pandas as pd
pd.set_option('display.max_rows', 200)
pd.set_option('display.max_column', 2500)
pd.set_option('display.max_colwidth', 2500)\

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import altair as alt
# ! pip install altair
pd.set_option('display.max_rows', 200)
pd.set_option('display.max_column', 50)
%matplotlib inline

In [2]:
df = get_data("bike")

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
0,1,1/1/2011,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,16
1,2,1/1/2011,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,40
2,3,1/1/2011,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,32
3,4,1/1/2011,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,13
4,5,1/1/2011,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,1

In [3]:
print(get_data("bank"))

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

       age           job   marital  education default  balance housing loan  \
0       58    management   married   tertiary      no     2143     yes   no
1       44    technician    single  secondary      no       29     yes   no
2       33  entrepreneur   married  secondary      no        2     yes  yes
3       47   blue-collar   married    unknown      no     1506     yes   no
4       33       unknown    single    unknown      no        1      no   no
...    ...           ...       ...        ...     ...      ...     ...  ...
45206   51    technician   married   tertiary      no      825      no   no
45207   71       retired  divorced    primary      no     1729      no   no
45208   72       retired   married  secondary      no     5715      no   no
45209   57   blue-collar   married  secondary      no      668      no   no
45210   37  entrepreneur   married  secondary      no     2971      no   no

         contact  day month  duration  campaign  pdays  previous poutcome  \
0        unknown    5   may       261         1     -1         0  unknown
1        unknown    5   may       151         1     -1         0  unknown
2        unknown    5   may        76         1     -1         0  unknown
3        unknown    5   may        92         1     -1         0  unknown
4        unknown    5   may       198         1     -1         0  unknown
...          ...  ...   ...       ...       ...    ...       ...      ...
45206   cellular   17   nov       977         3     -1         0  unknown
45207   cellular   17   nov       456         2     -1         0  unknown
45208   cellular   17   nov      1127         5    184         3  success
45209  telephone   17   nov       508         4     -1         0  unknown
45210   cellular   17   nov       361         2    188        11    other

      deposit
0          no
1          no
2          no
3          no
4          no
...       ...
45206     yes
45207     yes
45208     yes
45209      no
45210      no

[45211 rows x 17 columns]

In [19]:
df_grpd = df.groupby("cyl")['mpg'].count().reset_index(name = 'number of cars')
df_grpd
fig = plt.figure(figsize=(8, 5))
sns.barplot(x="cyl", y="number of cars", data=df_grpd)

KeyError: 'cyl'