In [18]:
import numpy as np
import pandas as pd
import pycaret.datasets as cds

# [UCI Air Quality](https://archive.ics.uci.edu/ml/datasets/air+quality)

The dataset contains 9358 instances of hourly averaged responses from an array of 5 metal oxide chemical sensors embedded in an Air Quality Chemical Multisensor Device. The device was located on the field in a significantly polluted area, at road level,within an Italian city. Data were recorded from March 2004 to February 2005 (one year)representing the longest freely available recordings of on field deployed air quality chemical sensor devices responses. Ground Truth hourly averaged concentrations for CO, Non Metanic Hydrocarbons, Benzene, Total Nitrogen Oxides (NOx) and Nitrogen Dioxide (NO2) and were provided by a co-located reference certified analyzer. Evidences of cross-sensitivities as well as both concept and sensor drifts are present as described in De Vito et al., Sens. And Act. B, Vol. 129,2,2008 (citation required) eventually affecting sensors concentration estimation capabilities. Missing values are tagged with -200 value.
This dataset can be used exclusively for research purposes. Commercial purposes are fully excluded.

## Features

Date (DD/MM/YYYY)
Time (HH.MM.SS)
CO_GT - True hourly averaged concentration CO in mg/m^3
PT08_S1_CO - PT08.S1 (tin oxide) hourly averaged sensor response (nominally CO targeted)
C6H6_GT- True hourly averaged overall Non Metanic HydroCarbons concentration in microg/m^3 (reference analyzer)
True hourly averaged Benzene concentration in microg/m^3 (reference analyzer)
PT08_S2_NMHC- PT08.S2 (titania) hourly averaged sensor response (nominally NMHC targeted)
Nox_GT- True hourly averaged Nitric oxide concentration in ppb (reference analyzer)
PT08_S3_Nox- PT08.S3 (tungsten oxide) hourly averaged sensor response (nominally NOx targeted)
NO2_GT- True hourly averaged NO2 concentration in microg/m^3 (reference analyzer)
PT08_S4_NO2- PT08.S4 (tungsten oxide) hourly averaged sensor response (nominally NO2 targeted)
PT08_S5_O3 - PT08.S5 (indium oxide) hourly averaged sensor response (nominally O3 targeted)
T - Temperature in Â°C
RH- Relative Humidity (%)
AH - Absolute Humidity

In [19]:
airQ_df = cds.get_data("airquality")
airQ_df.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2004-03-10,18:00:00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,2004-03-10,19:00:00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,2004-03-10,20:00:00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,2004-03-10,21:00:00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,2004-03-10,22:00:00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888

In [20]:
airQ_df.columns

Index(['Date', 'Time', 'CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)',
       'PT08.S2(NMHC)', 'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)',
       'PT08.S5(O3)', 'T', 'RH', 'AH'],
      dtype='object')

In [21]:
airQ_df['DateTime'] = airQ_df.Date + ' ' + airQ_df.Time
airQ_df['DateTime'] = pd.to_datetime(airQ_df.DateTime)
airQ_df.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,DateTime
0,2004-03-10,18:00:00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578,2004-03-10 18:00:00
1,2004-03-10,19:00:00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255,2004-03-10 19:00:00
2,2004-03-10,20:00:00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502,2004-03-10 20:00:00
3,2004-03-10,21:00:00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867,2004-03-10 21:00:00
4,2004-03-10,22:00:00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888,2004-03-10 22:00:00

In [22]:
airQ_df = airQ_df.rename(columns={
    "CO(GT)": "CO_GT",
    "PT08.S1(C0)": "PT08_S1_CO",
    "NMHC(GT)": "NMHC_GT",
    "C6H6(GT)": "C6H6_GT",
    'PT08.S2(NMHC)': "PT08_S2_NMHC",
    'NOx(GT)': "Nox_GT",
    'PT08.S3(NOx)': "PT08_S3_Nox",
    'NO2(GT)': "NO2_GT",
    'PT08.S4(NO2)': "PT08_S4_NO2",
    'PT08.S5(O3)': "PT08_S5_O3"
})

In [23]:
airQ_df.dtypes

Date                    object
Time                    object
CO_GT                  float64
PT08.S1(CO)              int64
NMHC_GT                  int64
C6H6_GT                float64
PT08_S2_NMHC             int64
Nox_GT                   int64
PT08_S3_Nox              int64
NO2_GT                   int64
PT08_S4_NO2              int64
PT08_S5_O3               int64
T                      float64
RH                     float64
AH                     float64
DateTime        datetime64[ns]
dtype: object

In [24]:
airQ_df.shape

(9357, 16)

In [25]:
airQ_df.describe()

,CO_GT,PT08.S1(CO),NMHC_GT,C6H6_GT,PT08_S2_NMHC,Nox_GT,PT08_S3_Nox,NO2_GT,PT08_S4_NO2,PT08_S5_O3,T,RH,AH
count,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000
mean,-34.207524,1048.990061,-159.090093,1.865683,894.595276,168.616971,794.990168,58.148873,1391.479641,975.072032,9.778305,39.485380,-6.837604
std,77.657170,329.832710,139.789093,41.380206,342.333252,257.433866,321.993552,126.940455,467.210125,456.938184,43.203623,51.216145,38.976670
min,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000
25%,0.600000,921.000000,-200.000000,4.000000,711.000000,50.000000,637.000000,53.000000,1185.000000,700.000000,10.900000,34.100000,0.692300
50%,1.500000,1053.000000,-200.000000,7.900000,895.000000,141.000000,794.000000,96.000000,1446.000000,942.000000,17.200000,48.600000,0.976800
75%,2.600000,1221.000000,-200.000000,13.600000,1105.000000,284.000000,960.000000,133.000000,1662.000000,1255.000000,24.100000,61.900000,1.296200
max,11.900000,2040.000000,1189.000000,63.700000,2214.000000,1479.000000,2683.000000,340.000000,2775.000000,2523.000000,44.600000,88.700000,2.231000

In [26]:
airQ_df = airQ_df[airQ_df["T"] != -200]

In [27]:
airQ_df.to_csv("air.csv", index=False)

In [28]:
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns

In [29]:
airQ_df.corr()

,CO_GT,PT08.S1(CO),NMHC_GT,C6H6_GT,PT08_S2_NMHC,Nox_GT,PT08_S3_Nox,NO2_GT,PT08_S4_NO2,PT08_S5_O3,T,RH,AH
CO_GT,1.000000,0.117828,0.130118,0.068549,0.077325,0.532309,-0.081036,0.670099,-0.060633,0.122234,-0.130533,-0.020492,-0.187919
PT08.S1(CO),0.117828,1.000000,0.250628,0.883795,0.892964,0.564630,-0.771938,0.313563,0.682881,0.899324,0.048627,0.114606,0.135324
NMHC_GT,0.130118,0.250628,1.000000,0.136698,0.134317,0.000738,0.052192,0.106870,0.213850,0.111533,-0.068140,-0.014311,-0.123688
C6H6_GT,0.068549,0.883795,0.136698,1.000000,0.981950,0.538118,-0.735744,0.265851,0.765731,0.865689,0.198956,-0.061681,0.167972
PT08_S2_NMHC,0.077325,0.892964,0.134317,0.981950,1.000000,0.534201,-0.796703,0.285569,0.777254,0.880578,0.241373,-0.090380,0.186933
Nox_GT,0.532309,0.564630,0.000738,0.538118,0.534201,1.000000,-0.503144,0.821199,0.143447,0.622205,-0.242007,0.111562,-0.210105
PT08_S3_Nox,-0.081036,-0.771938,0.052192,-0.735744,-0.796703,-0.503144,1.000000,-0.287317,-0.538468,-0.796569,-0.145112,-0.056740,-0.232017
NO2_GT,0.670099,0.313563,0.106870,0.265851,0.285569,0.821199,-0.287317,1.000000,0.024735,0.338367,-0.139509,-0.082190,-0.257482
PT08_S4_NO2,-0.060633,0.682881,0.213850,0.765731,0.777254,0.143447,-0.538468,0.024735,1.000000,0.591144,0.561270,-0.032188,0.629641
PT08_S5_O3,0.122234,0.899324,0.111533,0.865689,0.880578,0.622205,-0.796569,0.338367,0.591144,1.000000,-0.027172,0.124956,0.070751
T,-0.130533,0.048627,-0.068140,0.198956,0.241373,-0.242007,-0.145112,-0.139509,0.561270,-0.027172,1.000000,-0.578621,0.656397
RH,-0.020492,0.114606,-0.014311,-0.061681,-0.090380,0.111562,-0.056740,-0.082190,-0.032188,0.124956,-0.578621,1.000000,0.167971
AH,-0.187919,0.135324,-0.123688,0.167972,0.186933,-0.210105,-0.232017,-0.257482,0.629641,0.070751,0.656397,0.167971,1.000000

In [30]:

px.imshow(airQ_df.corr())

In [31]:
px.scatter(airQ_df, x="PT08_S4_NO2", y="T")

regression of temperature T
by the amount of PT08.S4 (tungsten oxide) PT08_S4_NO2

In [32]:
from sklearn.model_selection import train_test_split
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

regr = linear_model.LinearRegression()

air_x = airQ_df["PT08_S4_NO2"]
air_y = airQ_df["T"]

splits = train_test_split(air_x, air_y, test_size=0.1, random_state=42)

air_x_train, air_x_test, air_y_train, air_y_test = list(map(lambda x: np.array(x).reshape(-1, 1),
                                                            splits))

# Train the model using the training sets
regr.fit(air_x_train, air_y_train)

# Make predictions using the testing set
air_y_pred = regr.predict(air_x_test)

# The coefficients
print("Coefficients: \n", regr.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(air_y_test, air_y_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(air_y_test, air_y_pred))

# Plot outputs
px.scatter(x=air_x_test.ravel(), y=air_y_test.ravel())

Coefficients:
 [[0.01433676]]
Mean squared error: 55.56
Coefficient of determination: 0.31

In [35]:
px.line(x=air_x_test.ravel(), y=air_y_pred.ravel())

## Mean squared error: 55.56
## Coefficient of determination: 0.31

In [34]:
import pickle
pickle.dump(regr, open("model.pkl", "wb"))